onboarding = false

[theme]
name = "terminal"
auto_switch = true

[keys]
prefix = "ctrl+space"

split_horizontal = "prefix+-"
split_vertical = "prefix+|"
close_pane = "prefix+x"

new_tab = "prefix+c"
rename_tab = "prefix+r"

next_agent = "shift+tab"

focus_agent = "prefix+ctrl+1..9"

[[keys.command]]
key = "alt+tab"
type = "shell"
command = "herdr tab focus $(herdr tab list 2>&1 | jq -r 'if .result.tabs[0].focused then .result.tabs[1].tab_id else .result.tabs[0].tab_id end')"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+h"
type = "pane"
command = "hunk diff"

[[keys.command]]
key = "prefix+y"
type = "shell"
command = "$HOME/.config/herdr/scripts/copy-hunk-user-comments.sh"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-splits.nav-left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-splits.nav-down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-splits.nav-up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-splits.nav-right"

[ui]
prompt_new_tab_name = false

agent_panel_sort = "spaces"
sidebar_collapsed_mode = "hidden"

[ui.toast]
delivery = "herdr"
