onboarding = false

[theme]
name = "terminal"
auto_switch = true

[keys]
prefix = "ctrl+space"

split_horizontal = "prefix+-"
split_vertical   = "prefix+|"
close_pane       = "prefix+x"

new_tab          = "prefix+c"
rename_tab       = "prefix+r"
close_tab        = "prefix+k"

[ui]
prompt_new_tab_name = false

[ui.toast]
delivery = "herdr"
