onboarding = false

[theme]
name = "terminal"
auto_switch = false

[keys]
prefix = "ctrl+space"

split_horizontal = "prefix+-"
split_vertical = "prefix+|"
close_pane = "prefix+x"

new_tab = "prefix+c"
rename_tab = "prefix+r"

goto = "prefix+g"

edit_scrollback = ""
copy_mode = "prefix+e"

navigate_workspace_up = "k"
navigate_workspace_down = "j"

previous_workspace = "prefix+p"
next_workspace = "prefix+n"
previous_tab = ""
next_tab = ""

focus_agent = "ctrl+shift+1..9"

[[keys.command]]
key = "shift+tab"
type = "shell"
command = "$HOME/.config/herdr/scripts/focus-next-done-agent.sh"
description = "Focus next done agent"

[[keys.command]]
key = "alt+tab"
type = "shell"
command = "herdr tab focus $(herdr tab list 2>&1 | jq -r '.result.tabs as $tabs | ($tabs[] | select(.focused).workspace_id) as $ws | [$tabs[] | select(.workspace_id == $ws)] as $ws_tabs | if $ws_tabs[0].focused then $ws_tabs[1].tab_id else $ws_tabs[0].tab_id end')"

[[keys.command]]
key = "prefix+l"
type = "pane"
command = "lazygit"
description = "Open Lazygit"

[[keys.command]]
key = "prefix+h"
type = "pane"
command = "hunk-dev diff"

[[keys.command]]
key = "prefix+f"
type = "pane"
command = "yazi"
description = "Open Yazi"

[[keys.command]]
key = "prefix+y"
type = "shell"
command = "$HOME/.config/herdr/scripts/copy-hunk-user-comments.sh"
description = "Copy user comments from hunk diff"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-splits.nav-left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-splits.nav-down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-splits.nav-up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-splits.nav-right"

[ui]
tab_bar_position = "bottom"
prompt_new_tab_name = false

agent_panel_sort = "spaces"
sidebar_collapsed_mode = "hidden"

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false

[experimental]
pane_history = true
