gui:
  scrollHeight: 5
git:
  pagers:
    - pager: delta --light --paging=never --file-decoration-style=none --hunk-header-decoration-style=none
    - pager: delta --dark --paging=never --file-decoration-style=none --hunk-header-decoration-style=none
    - pager: delta --dark --paging=never --file-decoration-style=none --hunk-header-decoration-style=none --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - pager: diff-so-fancy
os:
  editPreset: "custom"
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}})'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>")'
